@startuml
state program #pink
program : on chain account program

state wallet #yellow
wallet : payer wallet interaction

state screen #cyan
screen : visible or interactive content

state bumpslugcheck <<choice>>
state sign_up #cyan
state create_account
state sign_in #yellow
state slug_lookup
state authorize #yellow
state add_wallet #pink
state metered_page
state increment_meter #pink
state check_limit <<choice>>
state take_payment #pink
state account_page #cyan
state metered_page #cyan
state increment_limit #pink
state check_collect <<choice>>
state take_final_payment #pink
state delete_account

[*] -[bold]-> bumpslugcheck : navigate
bumpslugcheck --> sign_up : no bump slug
bumpslugcheck -[bold]-> slug_lookup : has bump slug

slug_lookup : find account using slug
slug_lookup -> sign_up : account not found
slug_lookup -[bold]-> check_limit : account found

sign_up : inform cost per fetch
sign_up : prompt limit amount
sign_up : enforce minimum on limit amount
sign_up : or sign-in with your wallet
sign_up --> create_account : sign up
sign_up --> sign_in : sign in

sign_in : payer wallet authorizes sign-in
sign_in : find account using payer wallet address
sign_in --> check_limit : account found
sign_in --> sign_up : account not found

create_account : enforce minimum on limit amount
create_account : limit amount
create_account : zero paid amount
create_account : zero used amount
create_account --> authorize

authorize : payer wallet authorizes contract with limit
authorize -> sign_up : wallet cancelled
authorize --> add_wallet : wallet signed

add_wallet : create a slug
add_wallet : update account with wallet address and slug
add_wallet --> check_limit

metered_page : display metered content as navigated
metered_page -[bold]-> [*] : navigate with slug

increment_meter : bump used amount on account by page increment
increment_meter -[bold]-> take_payment : sufficient unpaid
increment_meter -[bold]-> metered_page : insufficient unpaid

check_limit -> account_page : limit reached
check_limit -[bold]-> increment_meter : meter below limit

take_payment : make transfer of funds from wallet
take_payment --> account_page : payment failed
take_payment -r[bold]-> metered_page : payment succeeded

account_page: show current limit, cost per page
account_page: show used and paid amount
account_page: to change wallets, delete the account and sign-up with the new wallet
account_page: prompt new limit for renewal
account_page: enforce minimum on limit amount
account_page -> [*] : navigate with slug
account_page --> increment_limit : renew
account_page --> check_collect : delete

increment_limit: enforce minimum on limit amount
increment_limit: reduce used amount by paid amount
increment_limit: zero paid amount
increment_limit: set new limit amount
increment_limit: generate new slug
increment_limit --> [*] : navigate with slug

check_collect --> take_final_payment : sufficient unpaid
check_collect --> delete_account : insufficient unpaid

take_final_payment: same program as take_payment
take_final_payment --> delete_account

delete_account --> [*] : navigate without slug

@enduml
